#!/bin/bash

# -- validation -- 
if (($# != 1)); then
    echo "usage: FILENAME"
    exit 1
fi

if [[ ! -e $1 ]]; then
    echo "file does not exist"
    exit 1
fi

# -- ---
filename=$1

#nl -w1 -s". " $filename | cut -d" " -f2,3,4 --complement | sort -k2  

#cat <(nl -w1 -s". " $filename | cut -d" " -f2,3,4 --complement | sort -k2)

#awk '{print NR". "$0}' $filename

exit 0

