#!/bin/bash

#last_modified=$(find ~ -type f -printf"T@ %p\n" | sort -k1 | head -n1 | cut -d" " -f2)

#cat /etc/passwd | cut -d":" -f6

error_log=$(mktemp)
stats=$(mktemp)

while read home_dir; do
	#echo $home_dir
	if [[ ! -x $home_dir ]]; then 
		#echo " locked: $home_dir"
		continue
	fi
	find $home_dir -maxdepth 2 -type f -exec stat -c "%Y %n %U" {} \; 2> $error_log 1>stats
done < <(cat /etc/passwd | cut -d":" -f6)

cat stats | sort -k1 -r | head -n1 | cut -d" " -f2-

#last_modified=$(find /home -maxdepth 2 -type f -exec stat -c"%Y %n" {} + 2>/dev/null | sort -k1 -r | head -n1 | cut -d" " -f2)


