#!/bin/bash

#last_modified=$(find ~ -type f -printf"T@ %p\n" | sort -k1 | head -n1 | cut -d" " -f2)

last_modified=$(find /home/* -maxdepth 1 -type f -exec stat -c"%Y %n" {} + 2>/dev/null | sort -k1 -r | head -n1 | cut -d" " -f2)


echo $last_modified

stat -c "%U %n" $last_modified
